[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/hotel-details"
  to = "/travel"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
